name = "Davidbence005"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "Davidbence005_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "Davidbence005.wasm"
command = "npm run build:release"
